sudo: required
language: generic

services:
- docker

install:
- curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
- chmod +x skaffold
- sudo mv skaffold /usr/local/bin

script:
- env
- skaffold build --profile travis-ci